### ISSUE TITLE
CSV missing error when using only TCX?

### ISSUE THREAD

**Issue by berg0449** [psndcsrv/ifit-convert#2]
Are you expecting both the TCX and CSV input files from ifit?  I tried using just TCX file and got error CSV does not exist.  Using downloaded zip of 1.01.

d:\Development\GIT\ifit-convert
>java -jar ifit-convert.jar running d:\temp\iFitWorkouts\2022_02_03_18_02_2021_Boston_Marathon®_–_Part_1.tcx
15:47:26.929 [main] INFO  com.ungerdesign.ifit.Application - Got arguments: [running, d:\temp\iFitWorkouts\2022_02_03_18_02_2021_Boston_Marathon«_û_Part_1.tcx]
15:47:26.932 [main] INFO  com.ungerdesign.ifit.Application - Got files (1): [d:\temp\iFitWorkouts\2022_02_03_18_02_2021_Boston_Marathon«_û_Part_1.tcx]
15:47:26.938 [main] ERROR com.ungerdesign.ifit.Application - The CSV file needs to exist, and be readable
15:47:26.941 [main] ERROR com.ungerdesign.ifit.Application - Failed to process file: d:\temp\iFitWorkouts\2022_02_03_18_02_2021_Boston_Marathon«_û_Part_1.tcx
java.lang.RuntimeException: The CSV file needs to exist, and be readable
        at com.ungerdesign.ifit.Application.handleFile(Application.java:71)
        at com.ungerdesign.ifit.Application.main(Application.java:34)

d:\Development\GIT\ifit-convert
>dir d:\temp\iFitWorkouts\2022_02_03_18_02_2021_Boston_Marathon®_–_Part_1.tcx
 Volume in drive D is DATA
 Volume Serial Number is DC73-1A34

 Directory of d:\temp\iFitWorkouts

02/22/2022  08:36 PM           826,027 2022_02_03_18_02_2021_Boston_Marathon®_–_Part_1.tcx
               1 File(s)        826,027 bytes
               0 Dir(s)  443,848,003,584 bytes free

d:\Development\GIT\ifit-convert

**Comment by berg0449** [comment]
Ignore this.  I see you need both files
